# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table ingrediente (
  id_ingrediente                bigint generated by default as identity not null,
  nombre_ingrediente            varchar(255) not null,
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_ingrediente primary key (id_ingrediente)
);

create table receta (
  id_receta                     bigint generated by default as identity not null,
  nombre_receta                 varchar(150) not null,
  descripcion_receta            varchar(255) not null,
  usuario_id_usuario            bigint,
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_receta primary key (id_receta)
);

create table receta_ingrediente (
  receta_id_receta              bigint not null,
  ingrediente_id_ingrediente    bigint not null,
  constraint pk_receta_ingrediente primary key (receta_id_receta,ingrediente_id_ingrediente)
);

create table usuario (
  id_usuario                    bigint generated by default as identity not null,
  nombre_usuario                varchar(255) not null,
  correo_usuario                varchar(255) not null,
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint pk_usuario primary key (id_usuario)
);

create index ix_receta_usuario_id_usuario on receta (usuario_id_usuario);
alter table receta add constraint fk_receta_usuario_id_usuario foreign key (usuario_id_usuario) references usuario (id_usuario) on delete restrict on update restrict;

create index ix_receta_ingrediente_receta on receta_ingrediente (receta_id_receta);
alter table receta_ingrediente add constraint fk_receta_ingrediente_receta foreign key (receta_id_receta) references receta (id_receta) on delete restrict on update restrict;

create index ix_receta_ingrediente_ingrediente on receta_ingrediente (ingrediente_id_ingrediente);
alter table receta_ingrediente add constraint fk_receta_ingrediente_ingrediente foreign key (ingrediente_id_ingrediente) references ingrediente (id_ingrediente) on delete restrict on update restrict;


# --- !Downs

alter table receta drop constraint if exists fk_receta_usuario_id_usuario;
drop index if exists ix_receta_usuario_id_usuario;

alter table receta_ingrediente drop constraint if exists fk_receta_ingrediente_receta;
drop index if exists ix_receta_ingrediente_receta;

alter table receta_ingrediente drop constraint if exists fk_receta_ingrediente_ingrediente;
drop index if exists ix_receta_ingrediente_ingrediente;

drop table if exists ingrediente;

drop table if exists receta;

drop table if exists receta_ingrediente;

drop table if exists usuario;

